# Generated by Django 4.0.3 on 2022-04-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_type', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('site_comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wind_direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wind_speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=1, max_digits=3, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitric_oxide', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('nitrogen_dioxide', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('nitrogen_oxides', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('pm10', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('pm2point5', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.dates')),
                ('station_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.station_details')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.temperature')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.times')),
                ('wind_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.wind_direction')),
                ('wind_speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.wind_speed')),
            ],
        ),
    ]
