# Generated by Django 4.0.3 on 2022-03-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tracker', '0002_alter_temperature_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wind_direction',
            name='direction',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
