# Generated by Django 4.0.3 on 2022-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tracker', '0003_alter_wind_direction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, unique=True),
        ),
        migrations.AlterField(
            model_name='wind_speed',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, unique=True),
        ),
    ]
