# Generated by Django 4.0.3 on 2022-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tracker', '0004_alter_temperature_temp_alter_wind_speed_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
