# Generated by Django 4.0.3 on 2022-03-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_tracker', '0006_alter_station_details_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitric_oxide', models.DecimalField(decimal_places=1, max_digits=20)),
                ('nitrogen_dioxide', models.DecimalField(decimal_places=1, max_digits=20)),
                ('nitrogen_oxides', models.DecimalField(decimal_places=1, max_digits=20)),
                ('pm10', models.DecimalField(decimal_places=1, max_digits=20)),
                ('pm2point5', models.DecimalField(decimal_places=1, max_digits=20)),
                ('pm1', models.DecimalField(decimal_places=1, max_digits=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.dates')),
                ('station_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.station_details')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.temperature')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.times')),
                ('wind_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.wind_direction')),
                ('wind_speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_tracker.wind_speed')),
            ],
        ),
    ]
