# Generated by Django 4.0.3 on 2022-03-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_tracker', '0007_station_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_data',
            name='pm1',
        ),
    ]
