# Generated by Django 4.0.3 on 2022-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tracker', '0009_alter_temperature_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_data',
            name='nitric_oxide',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='station_data',
            name='nitrogen_dioxide',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='station_data',
            name='nitrogen_oxides',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='station_data',
            name='pm10',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='station_data',
            name='pm2point5',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
    ]
